# Permalinks
permalink:           pretty

# Setup
title:               James Hoskins
tagline:             CLass Blog
url:                 jphoskins55.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              James Hoskins
  url:               
  email:             jphoskins48@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jphoskins55

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
